### ISSUE TITLE
您的pytorch是什么版本的啊？我运行时出现以下问题，谢谢

### ISSUE THREAD

**Issue by zhangyi-student** [Yaziwel/OverNet#1]
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/OverNet-master/OverNetModel.py", line 151, in <module>
    img=pickle.load(f)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by Yaziwel** [comment]
pickle.load那里是加载数据，你可以把那里删掉，随便生成一个数据，例如torch.zeros((1,3,64,64))

**Comment by zhangyi-student** [comment]
代码不全嘛？NameError: name 'ops' is not defined

**Comment by Yaziwel** [comment]
只写了一个模型

**Comment by FuzhiYang** [comment]
请问channel number是16嘛？
当channel number为16时，parameter number只有284K，paper里report的是0.9M。
请问是我miss掉什么东西了嘛？
